defaults:
  - _self_
  - modules: berrrt
  - utils
  - dataset: default
  - train: default

run_name:
  run_name: null
  model_type: berrrt

debug: true

dataset:
  sample: true

hydra:
  sweeper:
    params:
      bert: glob(*)
  run:
    dir: hydra_output/${now:%Y-%m-%d}/${now:%H-%M-%S}

utils:
  random_seed: 44
  model_output_path: model_output

project_name: berrrt
